name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: checkout
         uses: actions/checkout@v5
       - name: setup deno
         uses: denoland/setup-deno@v2
       - name: install deps
         run: deno install
       - name: build assets
         run: deno task build:all
       - name: release
         uses: softprops/action-gh-release@v2
         with:
           body_path: RELEASE.md
           files: dist/*